---
apiVersion: v1
kind: Service
metadata:
  name: stock-project
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: stock-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
